[package]
name = "rtweekend"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rtweekend"
path = "src/main.rs"

[lib]
name = "rtweekend"
path = "src/lib.rs"

[dependencies]
image = "0.23.14"
glam = "0.20.2"
rand = "0.8.4"
